version: 2.1

jobs:
  prep-echo:
    docker:
      - image: cimg/base:stable
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Create and environment
          command: |
            BUILD_ARGS="\"--build-arg HELLOWHO=Bob\""
            echo "export BUILD_ARGS=${BUILD_ARGS}" >> $BASH_ENV
  test-echo:
    docker:
      - image: cimg/base:stable
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Create and environment
          command: |
            BUILD_ARGS="\"--build-arg HELLOWHO=Bob\""
            echo "export BUILD_ARGS=${BUILD_ARGS}" >> $BASH_ENV
      - run:
          name: Test Echo
          command: |
            docker build -t docker-hello:latest ${BUILD_ARGS} .

workflows:
  test-bash-env:
    jobs:
      - prep-echo
      - test-echo:
          requires:
            - prep-echo
