version: 2.1

jobs:
  test-echo:
    docker:
      - image: cimg/base
    working_directory: ~/project
    steps:
      - checkout
      - run:
          command: |
            BUILD_ARGS="\"--build-arg HELLOWHO=Bob\""
            echo "export BUILD_ARGS=${BUILD_ARGS}" >> $BASH_ENV
      - run:
          name: Test Echo
          command: |
            docker build -t docker-hello:latest ${BUILD_ARGS} .

workflows:
  test-bash-env:
    jobs:
      - test-echo
